print( 3 > 2)
print( 4 > True)
print( -5 < False)
print( 3 >= 2)
print( 3 < 2)
print( 3 <= 2)
print( 3 == 2)
print( 2 == 2)
print( 2 == 2.0)
print( 3 != 2)
print( 3 != 3)
print( "ABC" == "abc")
print("ABC" <= "ABC")
